# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-22 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20181222_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='header',
            field=models.ImageField(default='customer/header/1.png', null=True, upload_to='customer\\header'),
        ),
    ]
