# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181224_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_sale',
            field=models.BooleanField(default=True),
        ),
    ]
