# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181224_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='normal_price',
            field=models.FloatField(default=100),
        ),
    ]
