# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_goods_normal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(default='shop/1.png', upload_to='shop/goodimages'),
        ),
    ]
