# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 01:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0007_goods_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receive_name', models.CharField(max_length=50, verbose_name='收货人')),
                ('receive_address', models.CharField(max_length=150, verbose_name='收货地址')),
                ('receive_phone', models.CharField(max_length=50, verbose_name='收货人电话')),
                ('receive_remark', models.CharField(max_length=150, verbose_name='备注信息')),
                ('order_time', models.DateTimeField()),
                ('total_money', models.FloatField()),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
                ('money', models.FloatField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
